[package]
name = "mini-redis"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
clap = { version = "4.3.8", features = ["derive"] }
